const date = new Date()
console.log(date)
// year, month, day, hours, minutes, seconds, milliseconds
const date1 = new Date(2026,0,2,3,45,50,567)
console.log(date1)
const date2 = new Date("2026-02-03T03:45:50.567Z")
console.log(date2)
console.log(date1.getFullYear())
console.log(date2.getTime())
console.log(Date.now())
console.log(date1.toDateString())
const date3 = new Date("2026-12-25")
console.log(date3)
const date4 = new Date(0)
console.log(date4)
const date5 = new Date(1700000000000)
console.log(date5)
const date6 = new Date()
console.log(date6.getFullYear)
console.log(date6.getMonth())
console.log(date6.getDate())
console.log(date6.getHours())
console.log(date6.getMinutes())
console.log(date6.getSeconds())
console.log(date6.getMilliseconds())
console.log(date6.getDay()) 
console.log(date6.toISOString())
console.log(date6.toDateString())
date6.setFullYear(2026)
console.log(date6)
date6.setMonth(11)
console.log(date6)
date6.setDate(31)
console.log(date6)
date6.setHours(22)
console.log(date6)
date6.setMinutes(45)
console.log(date6)
date6.setSeconds(30)
console.log(date6)
date6.setMilliseconds(564)
console.log(date6)